# Generated by Django 4.0.1 on 2022-07-19 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Custumuser',
        ),
    ]
