# Generated by Django 4.0.1 on 2022-07-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custum_user',
            name='actif',
            field=models.BooleanField(default=True, verbose_name='actif'),
        ),
        migrations.AddField(
            model_name='custum_user',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='avatars'),
        ),
        migrations.AddField(
            model_name='custum_user',
            name='is_first_con',
            field=models.BooleanField(default=True, verbose_name='first connection'),
        ),
    ]
