# Generated by Django 4.0.1 on 2022-07-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_custum_user_actif_custum_user_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custum_user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars'),
        ),
    ]
