# Generated by Django 4.0.6 on 2022-08-03 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_numero_personne_delete_custum_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='personne',
            name='is_encadreur',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
