# Generated by Django 4.0.1 on 2022-08-01 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assemblee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_assemblee', models.CharField(max_length=80)),
                ('coordonnees_localisation', models.TextField(blank=True, null=True)),
                ('pays', models.CharField(max_length=8)),
                ('vile', models.CharField(max_length=50)),
                ('Encadreur', models.ForeignKey(default='Assemblée vacante', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Encandreur', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoAssemble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='PhotoAssemblee')),
                ('assemblee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.assemblee')),
            ],
        ),
    ]
