# Generated by Django 4.0.1 on 2022-08-01 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_assemblee_quartier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assemblee',
            old_name='vile',
            new_name='ville',
        ),
    ]
