# Generated by Django 4.0.1 on 2022-08-01 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_vile_assemblee_ville'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblee',
            name='Type_encadreur',
            field=models.CharField(choices=[('Sertiteur', 'Sertiteur'), ('Pasteur', 'Pasteur'), ('Délégué Pastoral', 'Délégué Pastoral'), ('Diacre', 'Diacre')], default='Sertiteur', max_length=50),
        ),
    ]
