# Generated by Django 4.0.1 on 2022-08-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_assemblee_type_encadreur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemblee',
            name='Type_encadreur',
            field=models.CharField(choices=[('Serviteur', 'Serviteur'), ('Pasteur', 'Pasteur'), ('Délégué Pastoral', 'Délégué Pastoral'), ('Diacre', 'Diacre')], default='Serviteur', max_length=50),
        ),
    ]
