# Generated by Django 4.0.6 on 2022-08-03 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_assemblee_encadreur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour', models.CharField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Pasteur'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi'), ('Dimanche', 'Dimanche')], max_length=50)),
                ('Heure', models.TimeField()),
                ('assemble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assamble_programme', to='main.assemblee')),
            ],
        ),
    ]
