# Generated by Django 4.0.6 on 2022-08-03 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_programme'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='Titre',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
