# Generated by Django 4.0.6 on 2022-08-06 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_programme_jour'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblee',
            name='Continent',
            field=models.CharField(choices=[('Amérique', 'Amérique'), ('Afrique', 'Afrique'), ('Europe', 'Europe'), ('Asie', 'Asie')], default='Afrique', max_length=50),
        ),
    ]
